# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64cde7f7facb43b9719cb12fca5beec704ed9974f439c5ea383107ba942b0e4a6821215b033fde08bac7d5fe276f45893c006e3e30fd1db46883865d2ba60d4c

test:
  secret_key_base: 47cd0319f68988ffd1c511d43f242d44cc510579c6652a333c5853d0899189523ca38ee3f0f72c705c473c19a69608c2fe39cef838f906f83c8005914c147f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
